--- Day 3: Gear Ratios ---
You and the Elf eventually reach a gondola lift station; he says the gondola lift will take you up to the water source, but this is as far as he can bring you. You go inside.

It doesn't take long to find the gondolas, but there seems to be a problem: they're not moving.

"Aaah!"

You turn around to see a slightly-greasy Elf with a wrench and a look of surprise. "Sorry, I wasn't expecting anyone! The gondola lift isn't working right now; it'll still be a while before I can fix it." You offer to help.

The engineer explains that an engine part seems to be missing from the engine, but nobody can figure out which one. If you can add up all the part numbers in the engine schematic, it should be easy to work out which part is missing.

The engine schematic (your puzzle input) consists of a visual representation of the engine. There are lots of numbers and symbols you don't really understand, but apparently any number adjacent to a symbol, even diagonally, is a "part number" and should be included in your sum. (Periods (.) do not count as a symbol.)

Here is an example engine schematic:

467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
In this schematic, two numbers are not part numbers because they are not adjacent to a symbol: 114 (top right) and 58 (middle right). Every other number is adjacent to a symbol and so is a part number; their sum is 4361.

Of course, the actual engine schematic is much larger. What is the sum of all of the part numbers in the engine schematic?

--- Part Two ---
The engineer finds the missing part and installs it in the engine! As the engine springs to life, you jump in the closest gondola, finally ready to ascend to the water source.

You don't seem to be going very fast, though. Maybe something is still wrong? Fortunately, the gondola has a phone labeled "help", so you pick it up and the engineer answers.

Before you can explain the situation, she suggests that you look out the window. There stands the engineer, holding a phone in one hand and waving with the other. You're going so slowly that you haven't even left the station. You exit the gondola.

The missing part wasn't the only issue - one of the gears in the engine is wrong. A gear is any * symbol that is adjacent to exactly two part numbers. Its gear ratio is the result of multiplying those two numbers together.

This time, you need to find the gear ratio of every gear and add them all up so that the engineer can figure out which gear needs to be replaced.

Consider the same engine schematic again:

467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
In this schematic, there are two gears. The first is in the top left; it has part numbers 467 and 35, so its gear ratio is 16345. The second gear is in the lower right; its gear ratio is 451490. (The * adjacent to 617 is not a gear because it is only adjacent to one part number.) Adding up all of the gear ratios produces 467835

In [1]:
import pandas as pd
import numpy as np

with open('data/day_3.txt') as txtfile:
    input_day3 = txtfile.read()#.splitlines()

# Part 1

In [2]:
df = pd.DataFrame([list(i) for i in input_day3.splitlines()])
df

,0,1,2,3,4,5,6,7,8,9,...,130,131,132,133,134,135,136,137,138,139
0,.,6,7,9,.,.,.,.,.,6,...,.,.,.,6,8,7,.,.,.,.
1,.,.,.,.,.,.,.,.,.,.,...,9,2,.,.,.,.,.,.,.,.
2,.,.,.,.,.,.,.,.,.,.,...,.,*,.,.,.,.,.,.,.,.
3,.,.,.,.,.,.,.,.,.,.,...,.,5,7,9,.,.,.,.,.,.
4,.,.,.,.,.,.,.,5,6,6,...,.,.,.,.,.,.,.,.,.,.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,.,.,6,4,9,.,.,.,.,.,...,.,.,.,.,.,.,.,.,.,.
136,.,.,.,.,.,.,.,.,.,2,...,.,.,.,4,4,3,.,.,.,.
137,.,.,.,.,.,.,.,.,.,.,...,.,.,@,.,.,.,.,.,.,.
138,.,.,.,.,.,.,8,0,6,.,...,.,.,.,.,.,.,.,.,.,.
139,.,.,.,.,.,.,.,.,.,.,...,.,.,.,7,2,9,.,.,.,.

In [3]:
import re
ones = df.applymap(lambda x: not bool(re.search(r"\w|\.",x))).astype(int)
ones

,0,1,2,3,4,5,6,7,8,9,...,130,131,132,133,134,135,136,137,138,139
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
136,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
137,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
138,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
139,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
one_mask = (ones + ones.shift(-1).fillna(0) + ones.shift(1).fillna(0))\
    .pipe(lambda x: x + x.shift(-1,axis=1).fillna(0) + x.shift(1, axis=1).fillna(0)).astype(int)

one_mask

,0,1,2,3,4,5,6,7,8,9,...,130,131,132,133,134,135,136,137,138,139
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
4,0,0,0,0,0,1,1,1,0,0,...,1,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,0,0,0,0,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
136,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,0,0
137,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,0,0
138,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,0,0
139,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
numbers_one = df.applymap(lambda x: int(x in '0123456789'))
numbers_one

,0,1,2,3,4,5,6,7,8,9,...,130,131,132,133,134,135,136,137,138,139
0,0,1,1,1,0,0,0,0,0,1,...,0,0,0,1,1,1,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,1,1,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,0,0,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
136,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,1,1,0,0,0,0
137,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
138,0,0,0,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
139,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,1,0,0,0,0

In [6]:
twos = numbers_one * one_mask + numbers_one
twos

,0,1,2,3,4,5,6,7,8,9,...,130,131,132,133,134,135,136,137,138,139
0,0,1,1,1,0,0,0,0,0,1,...,0,0,0,1,1,1,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,2,2,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,2,2,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,2,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,0,0,1,1,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
136,0,0,0,0,0,0,0,0,0,1,...,0,0,0,2,1,1,0,0,0,0
137,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
138,0,0,0,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
139,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,1,0,0,0,0

In [7]:
numbers = df.applymap(lambda x: x * int(x in '0123456789') if x in '0123456789' else 0).astype(int)
numbers

,0,1,2,3,4,5,6,7,8,9,...,130,131,132,133,134,135,136,137,138,139
0,0,6,7,9,0,0,0,0,0,6,...,0,0,0,6,8,7,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,9,2,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,5,7,9,0,0,0,0,0,0
4,0,0,0,0,0,0,0,5,6,6,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,0,0,6,4,9,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
136,0,0,0,0,0,0,0,0,0,2,...,0,0,0,4,4,3,0,0,0,0
137,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
138,0,0,0,0,0,0,8,0,6,0,...,0,0,0,0,0,0,0,0,0,0
139,0,0,0,0,0,0,0,0,0,0,...,0,0,0,7,2,9,0,0,0,0

In [8]:
final_numbers = twos.astype(str).apply(lambda x: ''.join(x), axis=1)\
    .str.replace('0', '-')\
    .str.replace('\d*2\d*', repl=lambda x: '2' * (x.span()[1] - x.span()[0]), regex=True)\
    .str.replace('-', '1')\
    .apply(lambda x: pd.Series(list(x)))\
    .astype(int)\
    .replace({1: "", 2: 1})\
    .mul(numbers)\
    .replace("", "-")\
    .astype(str).apply(lambda x: ''.join(x), axis=1)\
    .str.findall("\d+")\
    .sum()
final_numbers
sum([int(x) for x in final_numbers])

528799

In [12]:
print(final_numbers[0:500])

['662', '71', '805', '862', '680', '811', '846', '855', '230', '92', '92', '360', '664', '881', '677', '934', '780', '8', '654', '959', '539', '21', '379', '969', '976', '872', '579', '566', '652', '809', '482', '394', '492', '303', '650', '38', '106', '385', '793', '865', '220', '349', '691', '392', '797', '11', '890', '870', '156', '733', '921', '203', '238', '188', '294', '58', '408', '677', '778', '104', '411', '706', '249', '638', '848', '948', '917', '817', '346', '69', '310', '118', '428', '785', '931', '217', '934', '475', '844', '885', '66', '587', '74', '773', '194', '107', '375', '826', '190', '498', '212', '398', '474', '925', '949', '213', '353', '853', '33', '164', '998', '325', '640', '823', '957', '746', '777', '264', '904', '457', '325', '390', '618', '265', '670', '165', '909', '634', '810', '503', '438', '904', '563', '345', '597', '758', '154', '941', '612', '691', '336', '837', '489', '462', '995', '106', '383', '911', '467', '44', '445', '765', '647', '464', '226', '151', '116', '249', '929', '500', '140', '18', '823', '454', '968', '118', '762', '8', '304', '620', '573', '878', '273', '572', '661', '527', '971', '259', '83', '983', '492', '166', '339', '978', '373', '340', '761', '758', '934', '550', '148', '25', '236', '624', '393', '62', '167', '716', '380', '873', '812', '362', '115', '537', '697', '159', '522', '41', '812', '13', '529', '374', '143', '109', '365', '952', '122', '555', '937', '674', '774', '371', '38', '304', '750', '715', '873', '819', '165', '928', '345', '77', '478', '743', '417', '802', '230', '509', '573', '219', '675', '865', '13', '25', '62', '4', '980', '145', '556', '278', '85', '442', '972', '541', '91', '614', '485', '680', '792', '541', '486', '653', '247', '778', '680', '980', '710', '494', '88', '825', '629', '439', '89', '430', '401', '660', '407', '883', '265', '438', '390', '388', '861', '798', '417', '551', '102', '332', '804', '463', '649', '188', '992', '754', '203', '912', '732', '490', '214', '134', '805', '934', '835', '622', '541', '861', '442', '874', '458', '955', '985', '172', '497', '310', '341', '644', '246', '909', '320', '893', '150', '717', '833', '178', '622', '681', '414', '612', '678', '336', '715', '407', '611', '42', '159', '97', '355', '954', '967', '120', '519', '382', '974', '539', '132', '702', '923', '905', '971', '453', '149', '717', '400', '618', '295', '644', '786', '287', '810', '908', '168', '903', '483', '750', '108', '570', '934', '523', '736', '889', '557', '913', '107', '852', '241', '974', '42', '268', '610', '894', '242', '150', '907', '924', '529', '267', '692', '505', '265', '95', '137', '347', '268', '753', '12', '955', '258', '854', '253', '15', '506', '559', '376', '892', '593', '682', '750', '10', '187', '540', '866', '437', '994', '730', '404', '703', '507', '126', '300', '315', '572', '793', '309', '518', '437', '182', '310', '176', '129', '882', '256', '249', '71', '76', '54', '910', '734', '445', '807', '75', '907', '477', '247', '855', '647', '558', '407', '129', '322', '235', '821', '767', '35', '824', '338', '55', '232', '814', '546', '582', '509', '270', '33', '673', '257', '793', '831', '805', '871', '701', '503', '710', '37', '897', '516', '330', '371', '324', '875', '293', '510', '332', '2', '558', '147', '926', '426', '142', '184', '746', '755', '285', '221', '571', '539', '644', '333', '499', '510', '257', '583', '408', '396', '493', '489', '380', '908', '711', '561', '24']

In [14]:
len(final_numbersal_numbers)

1064

# Part 2

In [134]:
stars = df.applymap(lambda x: x=='*').astype(int)
stars_mask = (stars + stars.shift(-1).fillna(0) + stars.shift(1).fillna(0))\
    .pipe(lambda x: x + x.shift(-1,axis=1).fillna(0) + x.shift(1, axis=1).fillna(0)).astype(int)

stars_mask

,0,1,2,3,4,5,6,7,8,9,...,130,131,132,133,134,135,136,137,138,139
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
4,0,0,0,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,0,0,0,0,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
136,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
137,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
138,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
139,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [151]:
stars_id = pd.DataFrame([[f'{r}+{c}' for c in range(df.shape[0])] for r in range(df.shape[1])]) * stars
stars_mask_id = (stars_id + stars_id.shift(-1).fillna('') + stars_id.shift(1).fillna(''))\
    .pipe(lambda x: x + x.shift(-1,axis=1).fillna('') + x.shift(1, axis=1).fillna(''))

stars_mask_id

,0,1,2,3,4,5,6,7,8,9,...,130,131,132,133,134,135,136,137,138,139
0,,,,,,,,,,,...,,,,,,,,,,
1,,,,,,,,,,,...,2+131,2+131,2+131,,,,,,,
2,,,,,,,,,,,...,2+131,2+131,2+131,,,,,,,
3,,,,,,,,,,,...,2+131,2+131,2+131,,,,,,,
4,,,,,,5+6,5+6,5+6,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,,,,,134+5,134+5,134+5,,,,...,,,,,,,,,,
136,,,,,,,,,,,...,,,,,,,,,,
137,,,,,,,,,,,...,,,,,,,,,,
138,,,,,,,,,,,...,,,,,,,,,,
139,,,,,,,,,,,...,,,,,,,,,,

In [135]:
twos_star = numbers_one * stars_mask + numbers_one
twos_star

,0,1,2,3,4,5,6,7,8,9,...,130,131,132,133,134,135,136,137,138,139
0,0,1,1,1,0,0,0,0,0,1,...,0,0,0,1,1,1,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,2,2,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,2,2,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,2,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,0,0,1,1,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
136,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,1,1,0,0,0,0
137,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
138,0,0,0,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
139,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,1,0,0,0,0

In [214]:
final_numbers = twos_star.astype(str).apply(lambda x: ''.join(x), axis=1)\
    .str.replace('0', '-')\
    .to_frame('name')\
    .apply(lambda x: re.sub('\d*2\d*',string=x["name"],
                            repl=lambda y: f"({max(stars_mask_id.loc[x.name, y.span()[0]], stars_mask_id.loc[x.name, y.span()[1]-1])}:{''.join(df.loc[x.name, y.span()[0]:y.span()[1]-1].tolist())})"),
           axis=1)\
    .str.findall("\([\d\+:]+\)")\
    .sum()

dicc_numbers = {}
for n in final_numbers:
    key = n.split(':')[0][1:]
    value = int(n.split(':')[1][:-1])
    if key not in dicc_numbers:
        dicc_numbers[key] = [value]
    else:
        dicc_numbers[key].append(value)

prod = 0
for val in dicc_numbers.values():
    if len(val)==2:
        prod += val[0] * val[1]

prod

84907174